#!/usr/bin/env bash

find . -type f | \
  while read i; do
    sed -i 's|https://k1ss.armaanb.net|https://k1ss.armaanb.net|g' ${i}
    sed -i 's|https://github.com/kiss-community|https://github.com/kiss-community|g' ${i}
  done
